categorias:
    path:     /
    defaults: { _controller: "uniMarcaBundle:categorias:index" }

categorias_show:
    path:     /{id}/show
    defaults: { _controller: "uniMarcaBundle:categorias:show" }
uni_marca_categorias:
    resource: "@uniMarcaBundle/Resources/config/routing/conSeguridad/categoriasSeguridad.yml"
    prefix:   /conSeguridad
