comentarios:
    path:     /
    defaults: { _controller: "uniMarcaBundle:comentarios:index" }

comentarios_show:
    path:     /{id}/show
    defaults: { _controller: "uniMarcaBundle:comentarios:show" }
uni_marca_comentarios:
    resource: "@uniMarcaBundle/Resources/config/routing/conSeguridad/comentariosSeguridad.yml"
    prefix:   /conSeguridad

