noticias:
    path:     /
    defaults: { _controller: "uniMarcaBundle:noticias:index" }

noticias_show:
    path:     /{id}/show
    defaults: { _controller: "uniMarcaBundle:noticias:show" }

noticias_new:
    path:     /new
    defaults: { _controller: "uniMarcaBundle:noticias:new" }

noticias_create:
    path:     /create
    defaults: { _controller: "uniMarcaBundle:noticias:create" }
    requirements: { _method: post }

noticias_edit:
    path:     /{id}/edit
    defaults: { _controller: "uniMarcaBundle:noticias:edit" }

noticias_update:
    path:     /{id}/update
    defaults: { _controller: "uniMarcaBundle:noticias:update" }
    requirements: { _method: post|put }

noticias_delete:
    path:     /{id}/delete
    defaults: { _controller: "uniMarcaBundle:noticias:delete" }
    requirements: { _method: post|delete }
    
noticias_buscar_autor:
    path:     /buscarautor
    defaults: { _controller: "uniMarcaBundle:noticias:buscarAutor" }
    
noticias_responder_autor:
    path:     /responderautor
    defaults: { _controller: "uniMarcaBundle:noticias:responderAutor" }
    requirements: { _method: post|put }
    
noticias_buscar_titulo:
    path:     /buscartitulo
    defaults: { _controller: "uniMarcaBundle:noticias:buscarTitulo" }
    
noticias_responder_titulo:
    path:     /respondertitulo
    defaults: { _controller: "uniMarcaBundle:noticias:responderTitulo" }
    requirements: { _method: post|put }
    
noticias_buscar_titulolike:
    path:     /buscartitulolike
    defaults: { _controller: "uniMarcaBundle:noticias:buscarTitulolike" }
    
noticias_responder_titulolike:
    path:     /respondertitulolike
    defaults: { _controller: "uniMarcaBundle:noticias:responderTitulolike" }
    requirements: { _method: post|put }
