noticias:
    path:     /
    defaults: { _controller: "uniMarcaBundle:noticias:index" }

noticias_show:
    path:     /{id}/show
    defaults: { _controller: "uniMarcaBundle:noticias:show" }
   
noticias_buscar_autor:
    path:     /buscarautor
    defaults: { _controller: "uniMarcaBundle:noticias:buscarAutor" }
    
noticias_responder_autor:
    path:     /responderautor
    defaults: { _controller: "uniMarcaBundle:noticias:responderAutor" }
    requirements: { _method: post|put }
    
noticias_buscar_titulo:
    path:     /buscartitulo
    defaults: { _controller: "uniMarcaBundle:noticias:buscarTitulo" }
    
noticias_responder_titulo:
    path:     /respondertitulo
    defaults: { _controller: "uniMarcaBundle:noticias:responderTitulo" }
    requirements: { _method: post|put }
    
noticias_buscar_titulolike:
    path:     /buscartitulolike
    defaults: { _controller: "uniMarcaBundle:noticias:buscarTitulolike" }
    
noticias_responder_titulolike:
    path:     /respondertitulolike
    defaults: { _controller: "uniMarcaBundle:noticias:responderTitulolike" }
    requirements: { _method: post|put }
    
uni_marca_noticias:
    resource: "@uniMarcaBundle/Resources/config/routing/conSeguridad/noticiasSeguridad.yml"
    prefix:   /conSeguridad
